### ISSUE TITLE
Harvest all from institution only harvests 1 or 2 collections, not all

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#101]
Team members report that running "Harvest All from Institution" button/command is not working as planned. It will harvest only one or two collections and then stop, not harvesting any others, forcing us to harvest seed by seed. I saw this occur repeatedly with Slipper Rock University. Leanne encountered it with College of Physicians.

**Comment by kelynch** [comment]
I can take a look at this as part of my work on #67

**Comment by kelynch** [comment]
This is addressed in #103.  Tested with an institution that had 5 seeds, each of which was harvested.  If it fails with Slippery Rock and CPP, I'd be happy to test with the exact seed info of 3+ seeds from them to see if there's a seed-specific issue at play.

**Comment by dorevabelfiore-temple** [comment]
Asked Leanne and Anastasia to test this functionality on other institutions. Will get back to you. Thanks @kelynch !

**Comment by dorevabelfiore-temple** [comment]
Issues reported with this functionality, although we are having some issue re-ingesting collections on test. Anastasia is testing and tracking her testing here: https://docs.google.com/spreadsheets/d/1PiOIz-c8_vJjtFxmig3pG3CQIZpMF09e-79kRdNL5VA/edit?ts=577d0adf#gid=0
