### ISSUE TITLE
Ability to find and replace OAI URL in Seed, Record Data

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#112]
One of our major Intermediate Providers is going to change URLS for their CONTENTdm servers in July 2016, which will affect their OAI endpoint. Temporarily there will be a redirect from the old to the new URL. To address this case and future URL changes:

Can we do a find and replace in the backend for:

a)OAI URL in every seed [highest priority]

b)URLS found in the record [lower priority if A can be accomplished]
e.g. identifier, thumbnail

Specs to be provided offline. Thanks!

**Comment by dorevabelfiore-temple** [comment]
Here are the URL changes. We are awaiting the date when these need to be changed:

OLD: http://contentdm1.accesspa.org/oai/oai.php 

NEW: http://digitalcollections.powerlibrary.org/oai/oai.php

**Comment by dorevabelfiore-temple** [comment]
Data live in the DPLA. Moving to Ready. Thanks.

**Comment by bibliotechy** [comment]
@dorevabelfiore-temple  Endpoint URLs for all accesspa seeds have been updated to the new endpoint URL. Tested with `MCC Montgazette NEW` and it appears that resumption tokens are being handled correctly, so it look slike it worked. Please confirm and close.

**Comment by dorevabelfiore-temple** [comment]
Looks good in test. Will have Anastasia test 2 more seeds, then you can do the same in Production.

**Comment by EliseTemple** [comment]
Tested good in test. Please do the same in production. Thanks!

**Comment by bibliotechy** [comment]
Done

**Comment by dorevabelfiore-temple** [comment]
Awesome. We will reharvest in late August for deployment to DPLA. Ready for close! Thanks.
