### ISSUE TITLE
URIs are case sensitive

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/dplah#141]
Our [current normalization](https://github.com/tulibraries/dplah/blob/develop/lib/harvest_utils.rb#L440) of rights fields URIs downcases them. URIs can be, and in the case of rightsstatements.org are, case sensitive, so this breaks links.

**Comment by dorevabelfiore-temple** [comment]
+1 Thanks for finding source & adding this.

**Comment by dorevabelfiore-temple** [comment]
Chad, this looks to be done. Is it complete? We tested in production and it looks good now.

**Comment by bibliotechy** [comment]
@dorevabelfiore-temple  Uhhh...I didn't do anything to fix this yet.

**Comment by dorevabelfiore-temple** [comment]
@bibliotechy OK let me do some more testing!

**Comment by dorevabelfiore-temple** [comment]
@bibliotechy This is interesting. @lfinnigan tested the PSU Benson collection in production this morning and it looked fine. I tested PSU Benson in test and now it does not display the capitalization / over-normalization. I could test more seeds tomorrow. http://test.padigital.org/catalog/dplapa:PSU_benson_228

**Comment by bibliotechy** [comment]
@dorevabelfiore-temple @lfinnigan So, the issue is only in the outbound OAI. That record has this element:

```xml
<dc:rights>http://rightsstatements.org/vocab/inc-ruu/1.0/</dc:rights>
```

As part of this ticket, I'm going to harmonize these displays.

**Comment by dorevabelfiore-temple** [comment]
@bibliotechy @lfinnigan Sounds good. Thanks.
