### ISSUE TITLE
In test and prod, missing right log doesn't have complete URL to record

### ISSUE THREAD

**Issue by lfinnigan** [tulibraries/dplah#143]
URLs in missing rights logs are incomplete (path but no domain). Example from test:
/aggregator-testing/catalog/dplapa:BRYNMAWR_castle_1477

Also, is that correct path now that domain has changed?

Log from test:
http://test.padigital.org/agg-logs/rights_missing.Bryn%20Mawr%20-%20Castle%20Collection%20of%20Natural%20History%20Illustrations.1476199675.txt

**Comment by bibliotechy** [comment]
@lfinnigan Thanks to some insight from  @kelynch, I have now pushed a change to dev that should fix this issue. I harvested the BRYNMAWR_castle collection, but did not get a rights report out to verify. Can you test or suggest a collection that will output a rights report so I can verify?

**Comment by dorevabelfiore-temple** [comment]
@bibliotechy @lfinnigan is on vacation this week. 

I ran the Philadelphia University Textile Trade cards in DEV and the URLS look good!

Other potential test collections:

PA Digital Test Collection - I set it up in DEV and it can be copied to TEST

http://dev.padigital.org/agg-logs/rights_missing.PA%20Digital%20CDM%20test.1476724130.txt

If you need more let me know.

**Comment by bibliotechy** [comment]
@dorevabelfiore-temple @lfinnigan 

I've pushed the changes to test and production now. Please verify and close the issue.

**Comment by dorevabelfiore-temple** [comment]
@bibliotechy @lfinnigan Confirmed in test and production. Closing.
