### ISSUE TITLE
OAI Harvester Identity Profile - needs correct aggregator name for instance

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#145]
Can the identification value be easily changed, or does it automatically get reset when the code is updated and moved from DEV to TEST or AGGREGATOR (Prod)?

http://test.padigital.org/oai?verb=Identify

<Identify>
<repositoryName>PA Digital</repositoryName>

Specifically can we change this value so that it always refers to TEST or DEV or AGGREGATOR? If that is a big hassle / overhead please tell me. Thanks.

**Comment by bibliotechy** [comment]
@dorevabelfiore-temple 

How's this http://dev.padigital.org/oai?verb=Identify

**Comment by dorevabelfiore-temple** [comment]
It's beautiful!

**Comment by bibliotechy** [comment]
This change now deployed to all sites.
