### ISSUE TITLE
Create script to remove all from production

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/dplah#150]
Can probably reuse the code from [Oral Histories](https://github.com/tulibraries/tul_ohist/blob/develop/lib/tasks/cdm.rake#L102) but that assumption needs to be tested.

**Comment by skng5** [comment]
@bibliotechy -

Remove all may be performed with the rake task:

```bash
rake oai:delete_all
```

**Comment by skng5** [comment]
Add to this task to create an Ansible playbook to delete all and repopulate the database.

**Comment by bibliotechy** [comment]
@skng5 The ansible play doesn't need to repopulate, just clear out what is there

**Comment by dorevabelfiore-temple** [comment]
I think this is complete for the recent (December) harvest. Thanks!
