### ISSUE TITLE
Omeka Passthrough type not displaying thumbnail in aggregator for new collections Closes #197

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#162]
I think this may be a bug. New collections I am testing with the Omeka passthrough have the correct identifiers listed for the object identifier, URL and thumbnail in the correct order in the metadata. It shows up correctly in the outbound OAI feed also. However, the thumbnail is not displaying in the Blacklight instance for TEST or DEV. However, the Free Library collections appear to be just fine and show thumbnails.

Example:

http://dev.padigital.org/catalog/dplapa:CLIVEDEN_CL000126 

<record>
<header>
<identifier>oai:libcollab.temple.edu:dplapa:CLIVEDEN_CL000126</identifier>
<datestamp>2017-02-17T17:48:05Z</datestamp>
</header>
<metadata>
<oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
<dc:title>Dish, Vegetable</dc:title>
<dc:description>
For use. Silverplated oval with lid having two handles, wire rim with molded edge on bowl, and makers marks under rim.
</dc:description>
<dc:contributor>Cliveden of the National Trust</dc:contributor>
<dc:type>Image</dc:type>
<dc:format>image/jpeg</dc:format>
<dc:identifier>dplapa:CLIVEDEN_CL000126</dc:identifier>
<dc:identifier>
http://cliveden.pastperfect-online.com/34148cgi/mweb.exe?request=record;id=71829AFD-1E58-4D59-A2E8-356360148246;type=101
</dc:identifier>
<dc:identifier>
http://cliveden.pastperfect-online.com/34148images/001/thumbs/CL000126.JPG
</dc:identifier>
<dc:source/>
<dc:relation>Cliveden Historical Images</dc:relation>
<dc:rights/>
</oai_dc:dc>
</metadata>
</record>
<record>

**Comment by dorevabelfiore-temple** [comment]
Other examples:
http://dev.padigital.org/catalog/dplapa:SLPa_pennsylvaniagerm03penn_2

http://test.padigital.org/catalog/dplapa:USCR_penmansartjourna01unse

http://test.padigital.org/?_=1487707345358&f%5Bcollection_name_sim%5D%5B%5D=Historic+Dental+Museum+Collection&f%5Bcontributing_institution_sim%5D%5B%5D=Temple+University

I can also provide more if that is helpful.

**Comment by dorevabelfiore-temple** [comment]
Here are some of the example CSV files that are causing issues. While the metadata is minimal, the mappings are exactly the same as the FLP files, which are working correctly. The ordering may be slightly different, but the order of identifiers is the same, and appear correctly in the outbound xml.

https://drive.google.com/open?id=0B-icpMLW3cRXLUhzN2JNRW05bUU

https://drive.google.com/open?id=0B-icpMLW3cRXMEZQMWFkb3hCSVU

https://drive.google.com/open?id=0B-icpMLW3cRXbjRITDFlbDBBZEU

**Comment by rlappel** [comment]
@kelynch this is now affecting our current harvest...any progress?
