### ISSUE TITLE
Seeds found with extra null value in array in dc:rights outbound feed field

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#163]
UPENN seeds Print at Penn and Penn in Hand found with an extra null value as second value in array in dc:rights outbound OAI field in PROD.

This is causing problems for DPLA Harvest.

**Comment by dorevabelfiore-temple** [comment]
CF: note from DPLA  (user: dpla ; pw: quality) test QA site:

http://cqa-pa.dp.la:8080/qa/compare?id=8c7d0c6ce811b63e8e1792edb7e47913

**Comment by dorevabelfiore-temple** [comment]
Example from today's reharvest in TEST - shows extra rights instance:
<record>
<header>
<identifier>
oai:libcollab.temple.edu:dplapa:UPENNPRT_PRINT_1314037
</identifier>
<datestamp>2017-03-01T15:49:49Z</datestamp>
</header>
<metadata>
<oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
<dc:title>
The new book of the horse / by Charles Richardson ; with twenty-nine coloured plates and numerous photographic illustrations and an extensive veterinary section.
</dc:title>
<dc:subject>Horses</dc:subject>
<dc:subject>Horses - Breeding</dc:subject>
<dc:subject>Horses - Diseases</dc:subject>
<dc:subject>Great Britain</dc:subject>
<dc:publisher>London : Cassell and company, limited, 1911</dc:publisher>
<dc:contributor>Richardson, Charles, 1853-1927</dc:contributor>
<dc:contributor>University of Pennsylvania</dc:contributor>
<dc:date>1911</dc:date>
<dc:identifier>dplapa:UPENNPRT_PRINT_1314037</dc:identifier>
<dc:identifier>
http://dla.library.upenn.edu/dla/print/pageturn.html?id=PRINT_1314037
</dc:identifier>
<dc:source/>
<dc:language>English</dc:language>
<dc:relation>Print at Penn</dc:relation>
<dc:rights>https://creativecommons.org/publicdomain/zero/1.0/</dc:rights>
<dc:rights/>
</oai_dc:dc>
</metadata>
</record>

**Comment by dorevabelfiore-temple** [comment]
And finally, I am not sure that this is related, but we are getting flags for each record of this collection not having a rights statement, yet the statements are there. See report: http://test.padigital.org/agg-logs/rights_missing.UPENN%20Print%20at%20Penn.1488383324.txt 

Obviously, a spurious report is not high priority, but it could relate to the base problem. Thanks.

**Comment by dorevabelfiore-temple** [comment]
Sorry for all the comments, but I thought it useful to add Scott's comment to this issue for maximum clarification:

+++++++++++++++++++++++++++++++
Scott Williams
10:43 AM (1 hour ago)

to Gretchen, me, Rachel, Anastasia, Chad, Delphine 
Hi all -- 

I just wanted to follow-up with a little more detail about why the edm:rights was failing for that record. Giving us rights in an array is necessarily a problem but it causes a problem when trying to identify a value that should go to edm:rights and not dc:rights. For URI values that should map to edm:rights I expected them to come across as a single string not wrapped in an array. If you need to send them in an array we can try to manage that that but adding more logical processing of rights values would not be my first choice for a solution.  

Apologizes as well about that capitalization issue. 

All the best,
Scott

**Comment by dorevabelfiore-temple** [comment]
Possibly related to #64

**Comment by gabrielgalson** [comment]
...

**Comment by dorevabelfiore-temple** [comment]
Interestingly enough, I now find Villanova records with the same issue. I don't know why this is happening though, as it is NOT present on Villanova's feed.

Example: "The Bold Privateer"

Original Villanova OAI-PMH is clean:
<header>
<identifier>oai:digital.library.villanova.edu:vudl:2201</identifier>
<datestamp>2014-01-08T14:08:33Z</datestamp>
<setSpec>vudl-system:CoreModel</setSpec>
<setSpec>vudl-system:CollectionModel</setSpec>
<setSpec>vudl-system:ResourceCollection</setSpec>
</header>
<metadata>
<oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
<dc:title>The Bold Privateer</dc:title>
<dc:creator>Guthrie, James, b. 1874.</dc:creator>
<dc:language>English</dc:language>
<dc:publisher>Dundrum : Cuala Press.</dc:publisher>
<dc:date>1911</dc:date>
<dc:subject>Bold privateer (Song)</dc:subject>
<dc:subject>Drum and fife (Poem)</dc:subject>
<dc:subject>Love -- Songs and music.</dc:subject>
<dc:subject>Privateering -- Songs and music.</dc:subject>
<dc:subject>Marching bands -- Poetry.</dc:subject>
<dc:subject>Circus performers -- Images.</dc:subject>
<dc:identifier>
https://digital.library.villanova.edu/Record/vudl:2201
</dc:identifier>
<dc:rights>http://creativecommons.org/licenses/by-sa/3.0/</dc:rights>
<dc:type>Text</dc:type>
</oai_dc:dc>
</metadata>
</record>


Production Aggregator Page: http://aggregator.padigital.org/catalog/dplapa:VNOVA_2201

Compare with this record in TEST:
<record>
<header>
<identifier>oai:libcollab.temple.edu:dplapa:VNOVA_34001</identifier>
<datestamp>2017-02-23T14:42:54Z</datestamp>
</header>
<metadata>
<oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
<dc:title>
Letter, To: William T. Sherman From: Ellie, May 1878.
</dc:title>
<dc:creator>Thackara, Eleanor Mary Sherman, 1859-1915.</dc:creator>
<dc:subject>Sherman, William T. (William Tecumseh), 1820-1891</dc:subject>
<dc:contributor>Villanova University</dc:contributor>
<dc:date>1878</dc:date>
<dc:type>Text</dc:type>
<dc:identifier>dplapa:VNOVA_34001</dc:identifier>
<dc:identifier>
https://digital.library.villanova.edu/Record/vudl:34001
</dc:identifier>
<dc:identifier>
https://digital.library.villanova.edu/files/vudl:34001/THUMBNAIL
</dc:identifier>
<dc:source/>
<dc:language>English</dc:language>
<dc:relation>Villanova University Digital Collections</dc:relation>
<dc:rights>http://creativecommons.org/licenses/by-sa/3.0/</dc:rights>
<dc:rights/>
</oai_dc:dc>
</metadata>
</record>

And in Prod:

<record><header><identifier>oai:libcollab.temple.edu:dplapa:VNOVA_333249</identifier><datestamp>2017-01-03T16:46:19Z</datestamp></header><metadata><oai_dc:dc xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"><dc:title>Chicago Ledger, v. XLVIII, no. 50, Saturday, December 11, 1920.</dc:title><dc:subject>Popular literature -- Specimens</dc:subject><dc:subject>Story papers -- Specimens</dc:subject><dc:publisher>Chicago, Ill. : W. D. Boyce Company</dc:publisher><dc:contributor>Villanova University</dc:contributor><dc:date>1920</dc:date><dc:type>Text</dc:type><dc:identifier>dplapa:VNOVA_333249</dc:identifier><dc:identifier>https://digital.library.villanova.edu/Record/vudl:333249</dc:identifier><dc:identifier>https://digital.library.villanova.edu/files/vudl:333249/THUMBNAIL</dc:identifier><dc:source/><dc:language>English</dc:language><dc:relation>Villanova University Digital Collections</dc:relation><dc:rights>http://creativecommons.org/licenses/by-sa/3.0/</dc:rights><dc:rights/></oai_dc:dc></metadata></record>

Prod and test have an additional <dc:rights/> value and I don't know where it is coming from. I thought this issue was limited to UPENN but possibly not.

--Doreva

**Comment by bibliotechy** [comment]
@dorevabelfiore-temple  @rlappel  #169 has now been merged and deployed to dev.
