### ISSUE TITLE
Contributing Institution Field not populating from DC picklist

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#164]
In DEV, the Contributing Institution field is not populating from the DC picklist. For example, instead of pulling from the DC:Contributor field, it is writing the string "DC Field: Contributor".

http://dev.padigital.org/?_=1489083762052&f%5Bcontributing_institution_sim%5D%5B%5D=DC+Field%3A+Contributor

**Comment by skng5** [comment]
I need a dataset that works with this the Contributing Institution DC Field set. Do you have an example of an OAI provider where this is working or has worked before on Production or Test?

**Comment by rlappel** [comment]
http://test.padigital.org/providers?utf8=%E2%9C%93&contributing_institution=Villanova+University; http://digital.library.villanova.edu/OAI/Server

http://test.padigital.org/providers?utf8=%E2%9C%93&contributing_institution=Scranton+Public+Library; http://content.lackawannadigitalarchives.org/oai/oai.php

**Comment by skng5** [comment]
In the instance that creates the problem, "contributing_institution_dc_field" value is set to "DC Field: Contributor". I need links to examples where this particular field is set to a non-blank value.

**Comment by rlappel** [comment]
This one should work: http://historicpittsburgh.org/oai2/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=pitt_collection.150

Keep in mind that the Historic Pittsburgh collections are a little wacky in the aggregator right now.

**Comment by skng5** [comment]
@rlappel - Thank you. I'll see if this helps me diagnose the issue.
