### ISSUE TITLE
Bad thumbnails in some Islandora collections

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#172]
Historic Pittsburgh uses a '%' in the thumbnail path of some images. This is being replaced with a space or not being translated. 

Example thumbnail: http://historicpittsburgh.org/islandora/object/pitt%3A200618.27.6.47/datastream/TN/view

http://dev.padigital.org/catalog/dplapa:UPITT_pitt_200618_27_6_47

**Comment by rlappel** [comment]
via @gabrielgalson 

The Presbyterian Historical Society's thumbnails still arn't showing up in Dev. Please investigate.

Link to thumbnail-less records:
http://dev.padigital.org/?_=1510953769025&f%5Bcontributing_institution_sim%5D%5B%5D=Presbyterian+Historical+Society

Here's how PHS's islandora is outbounding IDs:

dc:identifier.thumbnail
https://digital.history.pcusa.org/islandora/object/islandora%3A82627/datastream/TN/view/Japanese%20Internment%20Camp..jpg
</dc:identifier.thumbnail>
dc:identifier
https://digital.history.pcusa.org/islandora/object/islandora%3A82627
</dc:identifier>

The thumbnail link works. Could the double period before "jpg" be causing problems? Just an idea.

Thank you!

-GG

**Comment by gabrielgalson** [comment]
Update:  The Presbyterian Historical Society thumbnails are still not showing up in dev and test.  

Here's a screenshot of the 'PHS- Church Buildings' seed:

**Comment by skng5** [comment]
@gabrielgalson - The APS assets are missing thumbnails because the Common Repository Type is apparently missing for APS OAI Seeds on the test server.
