### ISSUE TITLE
Islandora Ingest Issues--Wipe Dev

### ISSUE THREAD

**Issue by rlappel** [tulibraries/dplah#173]
We deleted all records from this institution and from Historic Pittsburgh and this record won't go away. It's probably a duplicate that confused the system.

http://dev.padigital.org/?_=1490208550147&f%5Bintermediate_provider_sim%5D%5B%5D=Historic+Pittsburgh

**Comment by rlappel** [comment]
I also deleted the seed.

**Comment by rlappel** [comment]
There are now entire phantom seeds that were harvested along with a new Historic Pitt seed.

**Comment by rlappel** [comment]
This is all kinds of crazy and may need a deeper dive.

**Comment by dorevabelfiore-temple** [comment]
It might be worth considering dropping the jetty and testing 1 or 2 seeds to see what happens.

**Comment by rlappel** [comment]
Chad will wipe Fedora and Solr in Dev and transfer Prod's seeds.

**Comment by bibliotechy** [comment]
@rlappel Done
