### ISSUE TITLE
bepress thumbnail identifiers not outbounding

### ISSUE THREAD

**Issue by rlappel** [tulibraries/dplah#177]
When we tried to fix the too many identifiers issue, it must have stripped out the thumbnail image identifier which is no longer outbounding in our OAI.

**Comment by rlappel** [comment]
Our contact at Ursinus College noticed that their thumbnails were not displaying: https://dp.la/search?provider%5B%5D=Ursinus+College

I think this is related to how we currently provide at least three dc:identifier fields to the DPLA and order them based on the values they contain, ie the first holds a system-generated local Fedora ID that you ignore, the second holds a link back to the record in the partner's local system, and the last must hold a URL for a thumbnail.

We supressed records with "viewcontent" to get rid of one identifier for Bepress collections and it looked resolved on our end: http://aggregator.padigital.org/?_=1492433130406&f%5Bcontributing_institution_sim%5D%5B%5D=Ursinus+College Thomas Jefferson and Philadelphia College of Osteopathic Medicine collections also have blank thumbnails in the DPLA.

http://aggregator.padigital.org/oai?verb=GetRecord&identifier=oai:libcollab.temple.edu:dplapa:URSINUS_dutchmanmag_1010&metadataPrefix=oai_dc

If you look at that record there are only two <dc:identifiers>, one with the fedora id and one with the link.

Connected to #157

**Comment by kelynch** [comment]
Can I get a look at the OAI seed configuration in use in production for one seed for Ursinus, TJU, and Philadelphia College of Osteopathic Medicine?

**Comment by rlappel** [comment]
Kate,
Do you no longer have login credentials to Prod? Should I take a screenshot of each seed config?

**Comment by rlappel** [comment]
<img width="1316" alt="screen shot 2017-05-05 at 4 09 18 pm" src="https://cloud.githubusercontent.com/assets/23659656/25762605/60911c98-31ad-11e7-8fce-13d72d9b3af6.png">
<img width="1186" alt="screen shot 2017-05-05 at 4 09 34 pm" src="https://cloud.githubusercontent.com/assets/23659656/25762606/60921fee-31ad-11e7-8977-a2730c0a39c2.png">
<img width="1205" alt="screen shot 2017-05-05 at 4 10 18 pm" src="https://cloud.githubusercontent.com/assets/23659656/25762607/60973dc6-31ad-11e7-9a14-e0800e0af28e.png">

**Comment by kelynch** [comment]
Should be addressed by #185

**Comment by rlappel** [comment]
THANK YOU KATE!
