### ISSUE TITLE
APS (Islandora) not ingesting

### ISSUE THREAD

**Issue by EliseTemple** [tulibraries/dplah#189]
We are working on onboarding APS, but their collections are doing three things in dev:

1. Working normally: http://dev.padigital.org/catalog/dplapa:APS_graphics_7621
2. Not pulling identifiers at all (item identifier "APS_graphics_7607 still shows in URL though so it has to be pulling that from somewhere): http://dev.padigital.org/catalog/dplapa:APS_graphics_7607
3. Pulling identifiers, but not the correct trackback URL: http://dev.padigital.org/catalog/dplapa:APS_graphics_4773

Fun fact, all of these items come from the same collection! We looked at this collection's outbound OAI: http://diglib.amphilsoc.org/oai2?verb=ListRecords&metadataPrefix=oai_dc&set=graphics_Mss.B.P.31.15d

The only difference between a functional record and a non-functional one is the inclusion of an identifier within the body of the metadata record instead of just being in the header. However, the records with no identifier still show the item identifier in the record's URL on dev (as explained above). No metadata records include a traditional trackback URL or thumbnail record in the identifier fields.

**Comment by rlappel** [comment]
Can you test this collection in dev? That might be why it isn't working in test, the code hasn't been pushed.

**Comment by EliseTemple** [comment]
Collection tested in Dev.  Metadata comes through.

**Comment by EliseTemple** [comment]
* Thumbnails broken 
* Trackback URL issue

**Comment by EliseTemple** [comment]
looks like it is a mapping problem on their end.  will ask them to look at how the identifiers are mapped.

**Comment by rlappel** [comment]
Note: they do still have a legacy identifier: <dc:identifier xmlns:dc="http://purl.org/dc/elements/1.1/">graphics:165</dc:identifier> VERSUS 

<dc:identifier xmlns:dc="http://purl.org/dc/elements/1.1/">APSimg4892</dc:identifier> [legacy]

**Comment by rlappel** [comment]
Quick update: Scott is working on  removing or suppressing the legacy identifiers as a first step. 
It may be easier to suppress the legacies rather than figure out how to outbound the identifiers in a particular order. He will also try to provide a trackback URL, we can construct the thumbnail URL, because it always displays in the same pattern (assuming the initial URL is correct).

I gave him Aaron Brenner from UPitt's contact information so he can be in touch with Historic Pittsburgh's developers.

**Comment by kelynch** [comment]
What are the connection details for the call?  Zoom info not working this morning.  Also need more info on how I can be of assistance on this ticket as I'm currently largely unfamiliar with the development of the Islandora harvesting feature.
