### ISSUE TITLE
file.rename does not work when traversing partitions

### ISSUE THREAD

**Issue by AndrewGearhart** [tulibraries/dplah#2]
When utilizing file.rename, harvested xml files cannot be moved from /tmp to the directory specified in config.yaml if the config.yaml harvest location is on a different partition from the /tmp file. This happens, in particular, when running in a vagrant instance and locating the destination inside of the virtualbox shared folder.

The error occurs around Line 316 of lib/harvest_utils.rb
recommendations on fixing the error include using ruby fileUtilities to move the file instead of a File.rename. fileUtilities does not have the same-partition limitation that File.rename does.

**Comment by kelynch** [comment]
This is addressed in #4 , by replacing the reference to /tmp with 
````ruby
 new_file = "#{Rails.root.join('tmp')}/xml_hold_file.xml"
````
This contains the temp file within the application to maximize portability.
