### ISSUE TITLE
Free Library Rights Statements not in OAI Output

### ISSUE THREAD

**Issue by rlappel** [tulibraries/dplah#200]
Examples from all three collections: http://aggregator.padigital.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libcollab.temple.edu:dplapa:FLP_frk00501

http://aggregator.padigital.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libcollab.temple.edu:dplapa:FLP_mcaw090050

http://aggregator.padigital.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libcollab.temple.edu:dplapa:FLP_cdc285501

This is most likely related to the other Omeka Passthrough issues. We blanket their rights statements in the aggregator.

**Comment by rlappel** [comment]
Rachel will provide other examples where we blanket the rights statement.

**Comment by rlappel** [comment]
Susquehanna:
http://aggregator.padigital.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libcollab.temple.edu:dplapa:SUSQU_277

Scranton Public Library has two:
http://aggregator.padigital.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libcollab.temple.edu:dplapa:SCRANPL_scrchristma_12

**Comment by kelynch** [comment]
Addressed in #201
