### ISSUE TITLE
New Susquehanna Omeka Collections Not Ingesting

### ISSUE THREAD

**Issue by rlappel** [tulibraries/dplah#209]
The old ones from the same repo work.

http://test.padigital.org/agg-logs/Susquehanna%20University%20History%20Harvest%202017.1511967904.txt

http://test.padigital.org/agg-logs/Northumberland%20County%20Historical%20Society%20Harvest.1511966631.txt

**Comment by rlappel** [comment]
there is also a discrepancy of 6 records between test and prod.

**Comment by kelynch** [comment]
Addressed in #210
