### ISSUE TITLE
Ability to harvest all or delete all from one Intermediate Provider

### ISSUE THREAD

**Issue by EliseTemple** [tulibraries/dplah#67]
"Button to harvest all or delete all from one Intermediate Provider (e.g. POWER Library)
-- What is the best way to configure this?"

**Comment by dorevabelfiore-temple** [comment]
To be discussed with Metadata Team 6/16 re: functionality

**Comment by dorevabelfiore-temple** [comment]
Metadata Team concurs with this plan. Thank you!
