### ISSUE TITLE
Institutional page filter or pick list

### ISSUE THREAD

**Issue by EliseTemple** [tulibraries/dplah#71]
"\* Could we could get an institutional pick list or filter on so that we could see all seeds from one institution in order to work on them?
- Priority can be low now but would be important as the number of seeds escalates"

**Comment by EliseTemple** [comment]
[filterific](https://github.com/jhund/filterrific)? rails view?

**Comment by relaxing** [comment]
Definitely a pick list and not just a sort.

**Comment by dorevabelfiore-temple** [comment]
Spoke to @lfinnigan  and we would like to add one more pick list value if possible:

List all seeds where "In Production" flag/field value is set to "Yes".

Thanks!

**Comment by dorevabelfiore-temple** [comment]
Metadata Team needs to page through 30+ pages in TEST instance to get to specific seeds, which caused delays. This would be so helpful.
