### ISSUE TITLE
Add values to language code translation

### ISSUE THREAD

**Issue by EliseTemple** [tulibraries/dplah#80]
"""Please add the following to the translation table: Thanks!
-- swe  --> Swedish
-- heb --> Hebrew
-- afr  --> Afrikaans
-- fin  --> Finnish"

**Comment by dorevabelfiore-temple** [comment]
Marked as medium because codes went untranslated into live DPLA feed and somehow didn't get normalized on their end. Need before go-live of second data batch. Mid-Summer? Thanks.

**Comment by kelynch** [comment]
I can knock this one out quickly and put in a pull request ASAP.

**Comment by dorevabelfiore-temple** [comment]
Thanks!

--Doreva

On Wed, Apr 13, 2016 at 8:53 AM, Katherine Lynch <notifications@github.com>
wrote:

> I can knock this one out quickly and put in a pull request ASAP.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/tulibraries/dplah/issues/80#issuecomment-209419617>
>



-- 
Doreva Belfiore

Digital Projects Librarian
Digital Library Initiatives
Temple University Libraries
215-204-4942 (P)
215-204-3681 (F)

**Comment by kelynch** [comment]
Submitted PR #82

**Comment by bibliotechy** [comment]
Closed by #82
