### ISSUE TITLE
Create records reconciliation report between production aggregator and DPLA live

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#81]
Between submitting our OAI-PMH feed to the DPLA and their data normalization in KriKri, we lost a number of records. They can help us troubleshoot if we identify the records. Can you please create a reconciliation report comparing production records from DPLAH to live records in the DPLA?

Ideal fields in the report would be:
identifier
title
contributing institution
collection name

Thank you!

**Comment by EliseTemple** [comment]
Data doesn't look like it should from DPLA.

**Comment by bibliotechy** [comment]
Response from Scott at DPLA 

"
If you are just trying to identify missing records then you might try working it from the other side and generate the DPLA id for your source records and see which ones don't exist in the API. 

Here is the code to generate a DPLA ID is in KriKri:
https://github.com/dpla/KriKri/blob/e4efe16259c7867731e6042fd13ea9103d09bbe3/lib/krikri/md5_minter.rb

And using the example you sent you would call it this way:
Krikri::Md5Minter.create(*["oai:libcollab.temple.edu:dplapa:TEMPLE_p15037coll3_489"].compact)

>> "615f0221d75c72acd40ede56f7971265"
"

So it looks like I should be able to create this report after all.

**Comment by EliseTemple** [comment]
@bibliotechy  - notes from Leanne. hopefully you can look at this on Monday.

> Excellent. Is there a way to output the url easily? We can prepend the aggregator url easily to the IDs since it's consistent, but if it's easy for Chad to output that'd be great.
> 
> This report ran on the test aggregator. I'm assuming this can run on production, which is what we want, right?

**Comment by EliseTemple** [comment]
Notes from Doreva:
Not in DPLA report looks great and functions well. Is there any way to include the identifier http link to the object in the aggregator?

**Comment by EliseTemple** [comment]
Ask Chad to run script and he will run :)

**Comment by dorevabelfiore-temple** [comment]
OK will do. We can plan to run it right after we go live with the next set of records, and then calendar it as we get settled moving forward.
