### ISSUE TITLE
How far back do we need harvest logs?

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/dplah#86]
We have harvest logs going back to December for prod and test. We should set a policy deciding when to remove them.

**Comment by skng5** [comment]
We shouldn't keep them any longer than a month unless they contain significant errors.

**Comment by kelynch** [comment]
The length of time to retain might be a good discussion item with the Metadata Team if it hasn't already been one.  I'd suggest we make this a cron-schedulable task with the whenever gem so the time can be tweaked.  We should probably put some info into the log headers too letting the team know how long they'll be on the server and to save them locally if they want to retain a copy.

**Comment by EliseTemple** [comment]
I have asked Doreva to talk with the metadata team about this on Thursday.



On Tue, May 17, 2016 at 11:49 AM, Katherine Lynch <notifications@github.com>
wrote:

> The length of time to retain might be a good discussion item with the
> Metadata Team if it hasn't already been one. I'd suggest we make this a
> cron-schedulable task with the whenever gem so the time can be tweaked. We
> should probably put some info into the log headers too letting the team
> know how long they'll be on the server and to save them locally if they
> want to retain a copy.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tulibraries/dplah/issues/86#issuecomment-219762103>
>



-- 


*Elise Warshavsky*Digital Projects and Services Librarian
Digital Library Initiatives
Temple University
elise@temple.edu
215-204-6491

**Comment by bibliotechy** [comment]
@EliseTemple Thanks! That's what I was hoping for.

**Comment by dorevabelfiore-temple** [comment]
Spoke to metadata team. 2 people responded and agreed with me that we should follow in sync with DPLA harvests. We recommend a 90 day retention which would cover "quarterly". If that is not acceptable please come back with another proposal. Thanks.

**Comment by bibliotechy** [comment]
@dorevabelfiore-temple  Thanks! That works perfectly. 

I'm going to close this issues and create a low priority issue to implement a 90 day clean out policy.
