### ISSUE TITLE
PCOM - one Bepress test collection fails to ingest

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#90]
PCOM has Bepress. They have one collection (setspec = publication:pcom_digest) that harvests but fails to ingest. [http://digitalcommons.pcom.edu/do/oai/?verb=ListRecords&metadataPrefix=oai_dc&set=publication:pcom_digest] I attempted to harvest a subset of that collection for the 1920's that also failed to ingest. (setspec = publication:digest_twenties) In the past, I had a login to libcollab where I could attempt to run a manual rake test on a seed to attempt to troubleshoot but I understand that for security purposes you may not want that. Please see enclosed logs & let me know what can be done. LOW
[PCOM%20Digest.1463533081.txt](https://github.com/tulibraries/dplah/files/284860/PCOM.20Digest.1463533081.txt)
[PCOM%20Test%20Digest%201920's.1463535813.txt](https://github.com/tulibraries/dplah/files/284861/PCOM.20Test.20Digest.201920.s.1463535813.txt)

 priority - can push to future ingest time frame.

**Comment by bibliotechy** [comment]
Error message from the failed resque job:

```

No such file or directory @ rb_sysopen - /var/www/aggtest/samples/harvested/PCOMpublication:pcom_digest/_100_2016.xml

```

That slash in the middle of the filename looks like bad news.

**Comment by dorevabelfiore-temple** [comment]
pcom_digest is the name of the collection in bepress. Not sure where the /_ would have showed up from. Perhaps @kelynch can help with a suggestion where to start?

**Comment by EliseTemple** [comment]
Now is 2 collections that fail to ingest. + DO Class Photos.

**Comment by dorevabelfiore-temple** [comment]
We found out that the DO Class photos is having an OAI problem related to Bepress and Amazon S3 storage. I am working with Jackie, the PCOM staff member on that.  I found the problem with the seed - it belongs to multiple setspecs and only one of those functions correction. Go figure! Closing ticket.
